version: '3'
services: 
    ms-sql-server:
        image: "mssql:v1"
        environment: 
            SA_PASSWORD: "Organisation2018@"
            ACCEPT_EULA: "Y" 
            MSSQL_PID: Express
        ports: 
            - "1433:1433"
    auth:
        build: .
        ports:
            - "5000:80"
    